### ISSUE TITLE
Question@sagu about clippy config

### ISSUE THREAD

**Issue by andrieshiemstra** [DRFos/es_runtime#30]
the clippy workflow started giving errors about a 404 @ 
```
##[error]An action could not be found at the URI 'https://api.github.com/repos/actions-rs/clippy-check/tarball/annotations-fallback'
```

i updated this to v1 in https://github.com/DRFos/es_runtime/commit/cc59e11c744d3835574e2a4a2df119fd18aad42c

it works now but the actions takes only 7m instead of the usual 12-14 minutes

i can only find examples about the v1 variant so my question is what is the annotations-fallback variant and should this still work or is my modification to v1 ok?

**Comment by sagudev** [comment]
Hm, if I remember correctly annotations-fallback was because it would fail in PR because could not send annotations to GitHub. Build times changes with my commit https://github.com/DRFos/es_runtime/commit/220c6d0d6ce69c76c6825a7f12396add8a63e524. If I am not mistaken. I will check again, because I set annotations-fallback a long time ago.

**Comment by sagudev** [comment]
For build times you can check history. 
NOTE: On failed build caches do not update.

**Comment by sagudev** [comment]
If you check [changelog of clippy-check](https://github.com/actions-rs/clippy-check/blob/master/CHANGELOG.md#107---2020-06-17) you can see that they fixed attaching clippy report to the PR commits. As I assumed.

**Comment by andrieshiemstra** [comment]
Ah clear, thanks!
